apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  labels:
    app: node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api 
    spec:
      containers:
      - name: node-api
        image: 238343536427.dkr.ecr.eu-central-1.amazonaws.com/devopstask:2
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: node-api-config-map
                key: mongodb_uri
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: node-api-config-map
                key: node_env
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: node-api-secret
                key: secret

  